rules:
  - pattern: 'fis.metrics<name=(.*)>' 
    name: counter_$1
    help: some help
    type: COUNTER
    labels:
      route: $1
  - pattern: 'fis.metrics<name=camel.(.*)>' 
    name: camel_$1
    help: some help
    labels:
      route: $1
  - pattern: 'org.apache.camel<context=camel, type=routes, name=\"(.*)\"><>LastProcessingTime'
    name: camel_last_processing_time
    help: Last Processing Time [milliseconds]
    type: GAUGE
    labels:
      route: $1
