apiVersion: v1
kind: Service
metadata:
  name: ${project.artifactId}
  labels:
    expose: "true"
    app: ${project.artifactId}
    version: ${ocp-version}
spec:
  ports:
  - port: 8080
    name: http-8080
    targetPort: 8080
  - port: 8081
    targetPort: 8081
    name: http-8081

  